version: "3.8"


services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - static_data:/home/amir/code/staticfiles
    depends_on:
      - "web"
    restart: "on-failure"
    extra_hosts:
      - "myproject.com:127.0.0.1"

  
  web:
    build: .
    expose:
      - "8000"
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py initial_admin &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - docker.env
    volumes:
      - static_data:/home/amir/code/staticfiles
      - .:/home/amir/code:rw
    restart: "on-failure"
    image: project
    depends_on:
      - "db"

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=amir
      - POSTGRES_PASSWORD=amir
      - POSTGRES_DB=django_db
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
  static_data: